### ISSUE TITLE
api sample_metadata_markers error

### ISSUE THREAD

**Issue by xinsun1** [EBI-Metagenomics/holofood-database#7]
Hi,

Something is wrong with the `sample_metadata_markers` api.
The `count` returns 532. But the api is only available for 4 pages.

`https://www.holofooddata.org/api/sample_metadata_markers?page=5` and `page=6` gave error.

Please take a look. 
Thanks!

Cheers,
Xin

**Comment by SandyRogers** [comment]
Hello @xinsun1 , thank you for the bug report.
This has been fixed in #8 and deployed, so the latter pages now work.
This did require removing the `min_samples` and `min_animals` filters and associated counts in the response data, as there wasn't a pleasant way to keep those queries performant given the constraints of the database engine we are using – I hope that doesn't affect you.

Best,
Sandy
